version: '3.2'

services:
  db:
    restart: unless-stopped
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: "chainlink"
      POSTGRES_DB: "chainlink"
      POSTGRES_PASSWORD: "to584b1b2jflqorv"
    volumes:
      - chainlink_db:/var/lib/postgresql/data
    networks:
      edgeware:
    ports:
      - "0.0.0.0:5439:5432"

  # imports the 0xb90c7E3F7815F59EAD74e7543eB6D9E8538455D6 key into the CL db
  chainlink_key_import:
    image: smartcontract/chainlink:0.10.5
    command: local import /run/secrets/0xb90c7E3F7815F59EAD74e7543eB6D9E8538455D6
    volumes:
      - ./tmp/clroot/:/clroot/
    environment:
      - ROOT=/clroot
      - DATABASE_URL=postgresql://chainlink:to584b1b2jflqorv@db:5432/test2?sslmode=disable
    secrets:
      - '0xb90c7E3F7815F59EAD74e7543eB6D9E8538455D6'

  chainlink:
    image: smartcontract/chainlink:0.10.5
    command: local node -d -p /run/secrets/password -a /run/secrets/apicredentials
    restart: always
    volumes:
      - ./tmp/clroot/:/clroot/
    environment:
      - LOG_LEVEL=debug
      - ETH_URL=ws://52.91.75.170:9944 # Edgeware node
      - ROOT=/clroot
      - ETH_CHAIN_ID=2021
      - MIN_OUTGOING_CONFIRMATIONS=2
      - MINIMUM_CONTRACT_PAYMENT=1000000000000
      - CHAINLINK_DEV=true
      - CHAINLINK_TLS_PORT=0
      - DATABASE_URL=postgresql://chainlink:to584b1b2jflqorv@db:5432/test2?sslmode=disable
    depends_on:
      - chainlink_key_import
    networks:
      edgeware:
    ports:
      - 6688:6688
    secrets:
      - password
      - apicredentials

  price_mock:
    build:
      dockerfile: Dockerfile
      context: price-mock
    networks:
      edgeware:
        ipv4_address: 172.100.1.100
    ports:
      - "0.0.0.0:3000:3000"

  contracts:
    build:
      dockerfile: Dockerfile
      context: contracts
    environment:
      - GETH_HOST=52.91.75.170
    networks:
      edgeware:
    ports:
      - "127.0.0.1:8080:8080"

networks:
  edgeware:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.100.1.0/24

volumes:
  chainlink_db:

secrets:
  password:
    file: secrets/password.txt
  apicredentials:
    file: secrets/apicredentials.txt
  '0x9CA9d2D5E04012C9Ed24C0e513C9bfAa4A2dD77f':
    file: secrets/0x9CA9d2D5E04012C9Ed24C0e513C9bfAa4A2dD77f.json
  '0xb90c7E3F7815F59EAD74e7543eB6D9E8538455D6':
    file: secrets/0xb90c7E3F7815F59EAD74e7543eB6D9E8538455D6.json