name: Integration tests

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: 14.x
      - name: Run services
        run: docker-compose up -d
      - name: Test
        run: |
          while [ "$(curl -s -o /dev/null -w ''%{http_code}'' http://127.0.0.1:8080/)" != "200" ]; do echo "waiting for contract service..." && sleep 5; done && \
          while [ "$(curl -s -o /dev/null -w ''%{http_code}'' http://127.0.0.1:6688/)" != "200" ]; do echo "waiting for chainlink service..." && sleep 5; done && \
          docker-compose logs chainlink contracts && \
          cd integration && npm i && \
          CONTRACT_HOST=http://localhost:8080 CHAINLINK_URL=http://localhost:6688 \
          CHAINLINK_EMAIL=notreal@fakeemail.ch CHAINLINK_PASSWORD=twochains \
          PRICE_PROVIDER_URL=http://172.100.1.100:3000/price \
          npm run test
